using UnityEngine;

namespace Pinvestor.Game.Economy
{
    /// <summary>
    /// Per-instance valuation model for a placed company.
    /// Created on placement alongside CompanyHealthState.
    ///
    /// Initial valuation = purchase cost (from GameConfig company entry).
    /// The valuation appreciates as the company generates revenue, so cashing out a
    /// well-performing company before it collapses is a real economic decision:
    /// CashoutValue = PurchaseCost * cashout_rate + LifetimeRevenue * valuation_appreciation_rate.
    /// </summary>
    public sealed class CompanyValuationModel
    {
        /// <summary>The cost the player paid to place this company (from GameConfig).</summary>
        public float PurchaseCost { get; }

        /// <summary>
        /// The fraction of PurchaseCost returned on cashout.
        /// Sourced from GameConfig balance section key "cashout_rate".
        /// Falls back to <see cref="DefaultCashoutRate"/> if the key is absent.
        /// </summary>
        public float CashoutRate { get; }

        /// <summary>
        /// The fraction of lifetime revenue added to the cashout value.
        /// Sourced from GameConfig balance section key "valuation_appreciation_rate".
        /// Falls back to <see cref="DefaultAppreciationRate"/> if the key is absent.
        /// </summary>
        public float AppreciationRate { get; }

        /// <summary>Total revenue this company has generated since placement.</summary>
        public float LifetimeRevenue { get; private set; }

        /// <summary>Fallback cashout rate used when game-config.json does not define "cashout_rate".</summary>
        public const float DefaultCashoutRate = 0.5f;

        /// <summary>Fallback appreciation rate used when game-config.json does not define "valuation_appreciation_rate".</summary>
        public const float DefaultAppreciationRate = 0.3f;

        /// <summary>The key used to look up cashout rate in the balance config section.</summary>
        public const string CashoutRateKey = "cashout_rate";

        /// <summary>The key used to look up the appreciation rate in the balance config section.</summary>
        public const string AppreciationRateKey = "valuation_appreciation_rate";

        /// <summary>Computed cashout payout: recovered share of cost + appreciated share of earnings.</summary>
        public float CashoutValue => PurchaseCost * CashoutRate + LifetimeRevenue * AppreciationRate;

        public CompanyValuationModel(float purchaseCost, float cashoutRate)
            : this(purchaseCost, cashoutRate, DefaultAppreciationRate)
        {
        }

        public CompanyValuationModel(
            float purchaseCost,
            float cashoutRate,
            float appreciationRate)
        {
            PurchaseCost = Mathf.Max(0f, purchaseCost);
            CashoutRate = Mathf.Clamp01(cashoutRate);
            AppreciationRate = Mathf.Max(0f, appreciationRate);
        }

        /// <summary>
        /// Record revenue generated by this company. Called from the company wrapper's
        /// RevenueGenerator hook. Negative or zero amounts are ignored.
        /// </summary>
        public void RegisterRevenue(float amount)
        {
            if (amount <= 0f)
                return;

            LifetimeRevenue += amount;
        }
    }
}
