#!/usr/bin/env bash
set -euo pipefail

repo_root="${1:-$(pwd)}"
skill_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
catalog_path="${skill_dir}/references/content-catalog.md"
config_path="${repo_root}/Assets/Resources/GameConfig/game-config.json"
company_root="${repo_root}/Assets/ScriptableObjects/Company/Companies"

if [[ ! -f "${config_path}" ]]; then
  echo "Missing config file: ${config_path}" >&2
  exit 1
fi

if [[ ! -d "${company_root}" ]]; then
  echo "Missing company root: ${company_root}" >&2
  exit 1
fi

timestamp="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

config_company_ids="$(
  rg '"companyId"' "${config_path}" \
    | sed -E 's/.*"companyId"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/' \
    | sed '/^[[:space:]]*$/d'
)"

company_id_assets="$(
  find "${company_root}" -type f -name 'CompanyId.*.asset' \
    | sed -E 's#.*/CompanyId\.([^/]+)\.asset#\1#' \
    | sort -u
)"

company_card_assets="$(
  find "${company_root}" -type f -name 'CardData.Company.*.asset' \
    | sed -E 's#.*/CardData\.Company\.([^/]+)\.asset#\1#' \
    | sort -u
)"

company_categories="$(
  find "${company_root}" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort -u
)"

run_cycle_rounds="$(
  rg '"roundId"' "${config_path}" \
    | sed -E 's/.*"roundId"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/'
)"

shoot_speed="$(
  rg '"shootSpeed"' "${config_path}" \
    | sed -E 's/.*"shootSpeed"[[:space:]]*:[[:space:]]*([0-9.]+).*/\1/' \
    | head -n 1
)"

preview_length="$(
  rg '"previewLength"' "${config_path}" \
    | sed -E 's/.*"previewLength"[[:space:]]*:[[:space:]]*([0-9.]+).*/\1/' \
    | head -n 1
)"

has_booster_authoring="No"
has_run_theme_authoring="No"
has_market_news_authoring="No"

if find "${repo_root}/Assets/ScriptableObjects" -type d | rg -qi 'booster'; then
  has_booster_authoring="Yes"
fi
if find "${repo_root}/Assets/ScriptableObjects" -type d | rg -qi 'run.?theme'; then
  has_run_theme_authoring="Yes"
fi
if find "${repo_root}/Assets/ScriptableObjects" -type d | rg -qi 'market.?news|news'; then
  has_market_news_authoring="Yes"
fi

{
  echo "# Pinvestor Content Catalog"
  echo
  echo "Auto-generated by \`scripts/refresh-content-catalog.sh\`."
  echo
  echo "- Generated at (UTC): ${timestamp}"
  echo "- Repo root: \`${repo_root}\`"
  echo
  echo "## Companies (Runtime Config)"
  echo
  if [[ -z "${config_company_ids}" ]]; then
    echo "- None found in \`Assets/Resources/GameConfig/game-config.json\`."
  else
    while IFS= read -r c; do
      [[ -z "${c}" ]] && continue
      echo "- ${c}"
    done <<< "${config_company_ids}"
  fi
  echo
  echo "## Companies (Authored Assets)"
  echo
  echo "### Categories"
  if [[ -z "${company_categories}" ]]; then
    echo "- None"
  else
    while IFS= read -r cat; do
      [[ -z "${cat}" ]] && continue
      echo "- ${cat}"
    done <<< "${company_categories}"
  fi
  echo
  echo "### CompanyId Assets"
  if [[ -z "${company_id_assets}" ]]; then
    echo "- None"
  else
    while IFS= read -r c; do
      [[ -z "${c}" ]] && continue
      echo "- ${c}"
    done <<< "${company_id_assets}"
  fi
  echo
  echo "### CardData Assets"
  if [[ -z "${company_card_assets}" ]]; then
    echo "- None"
  else
    while IFS= read -r c; do
      [[ -z "${c}" ]] && continue
      echo "- ${c}"
    done <<< "${company_card_assets}"
  fi
  echo
  echo "## Other Domain Coverage Snapshot"
  echo
  echo "- Booster authoring directories under \`Assets/ScriptableObjects\`: ${has_booster_authoring}"
  echo "- Run theme authoring directories under \`Assets/ScriptableObjects\`: ${has_run_theme_authoring}"
  echo "- Market news authoring directories under \`Assets/ScriptableObjects\`: ${has_market_news_authoring}"
  echo
  echo "## Runtime Config Highlights"
  echo
  echo "- Ball shootSpeed: ${shoot_speed:-N/A}"
  echo "- Ball previewLength: ${preview_length:-N/A}"
  echo "- Run cycle rounds:"
  if [[ -z "${run_cycle_rounds}" ]]; then
    echo "  - None"
  else
    while IFS= read -r r; do
      [[ -z "${r}" ]] && continue
      echo "  - ${r}"
    done <<< "${run_cycle_rounds}"
  fi
  echo
  echo "## Naming Drift Warnings"
  echo
  echo "- Compare config IDs vs authored IDs for spacing/typo drift before finalizing designs."
  echo "- Known examples to verify in this repo: \`Stack Rabbit\` vs \`StackRabbit\`, \`VirtosoXR\` vs \`VirtuosoXR\`."
} > "${catalog_path}"

echo "Updated ${catalog_path}"
